<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'JvsRequire'                                    => __DIR__ . '/src/JvsRequire.php',
  'JvsRequire\View\Helper\JvsRequireHelper'       => __DIR__ . '/src/JvsRequire/View/Helper/JvsRequireHelper.php'
);
